// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prdmfcfnypagpsodbjqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByZG1mY2ZueXBhZ3Bzb2RianFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3OTc3NTYsImV4cCI6MjA1ODM3Mzc1Nn0.FaGQmrriPzkvsUF8Rz8yp3YOSmIVZ7ynj2k8J1on81o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);